/**
 * Branded export utilities for MAAROOF Ai.
 * Supports PDF (via browser print) and Excel (via xlsx) with brand header + disclaimer.
 */
import * as XLSX from "xlsx";
import maaroofLogo from "@/assets/maaroof-ai-logo.png";

export type ExportLang = "ar" | "en" | "ku";

export type ExportSection = {
  heading: string;
  // Either rows of [label, value] pairs, free text, or a tabular block.
  kind: "kv" | "text" | "table" | "list";
  rows?: Array<[string, string | number]>;
  text?: string;
  list?: string[];
  table?: { columns: string[]; data: (string | number)[][] };
};

export type ExportPayload = {
  title: string;
  subtitle?: string;
  lang?: ExportLang;
  sections: ExportSection[];
};

const BRAND = "MAAROOF Ai";
const PREVIOUS_BRAND = "formerly GEO-Iraq";
const SITE = "geoiraq.com";
const ECOSYSTEM = "Part of the Marouf system";

const DISCLAIMER: Record<ExportLang, string> = {
  ar: "إخلاء المسؤولية: المعلومات والتحليلات الواردة في هذا التقرير مُولَّدة بواسطة أدوات الذكاء الاصطناعي وأغراضها استرشادية فقط. لا تُعدّ نصيحة قانونية أو مالية أو تسويقية ملزمة. يتحمّل المستخدم وحده مسؤولية القرارات المبنية على هذا التقرير. © MAAROOF Ai — geoiraq.com",
  en: "Disclaimer: The information and analyses in this report are generated by AI tools and are provided for guidance only. They do not constitute binding legal, financial, or marketing advice. The user is solely responsible for decisions based on this report. © MAAROOF Ai — geoiraq.com",
  ku: "ڕەتکردنەوەی بەرپرسیارێتی: زانیاری و شیکارییەکانی ئەم ڕاپۆرتە بە ئامرازی AI دروستکراون و تەنها بۆ ڕێنمایی پێشکەش دەکرێن. ئامۆژگاری یاسایی، دارایی یان بازرگانی نییە. بەکارهێنەر بەرپرسیاری بڕیارەکانیەتی. © MAAROOF Ai — geoiraq.com",
};

const UI: Record<ExportLang, { generated: string; report: string }> = {
  ar: { generated: "أُنشئ في", report: "تقرير" },
  en: { generated: "Generated on", report: "Report" },
  ku: { generated: "دروستکرا لە", report: "ڕاپۆرت" },
};

const escapeHtml = (s: any) =>
  String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

function brandHeaderHtml(lang: ExportLang) {
  return `
    <header class="brand">
      <div class="logo" aria-hidden="true">
        <img src="${maaroofLogo}" alt="MAAROOF Ai" width="56" height="56" style="display:block;object-fit:contain;border-radius:10px;background:#fff;padding:2px"/>
      </div>
      <div class="brand-text">
        <div class="brand-name">${BRAND}</div>
        <div class="brand-prev">${PREVIOUS_BRAND}</div>
        <div class="brand-sub">${SITE} · ${ECOSYSTEM}</div>
      </div>
      <div class="meta">${UI[lang].generated} ${escapeHtml(new Date().toLocaleString())}</div>
    </header>
  `;
}

function sectionHtml(s: ExportSection): string {
  const h = `<h2>${escapeHtml(s.heading)}</h2>`;
  if (s.kind === "text" && s.text) {
    return `${h}<p class="prose">${escapeHtml(s.text).replace(/\n/g, "<br/>")}</p>`;
  }
  if (s.kind === "list" && s.list) {
    return `${h}<ul>${s.list.map((x) => `<li>${escapeHtml(x)}</li>`).join("")}</ul>`;
  }
  if (s.kind === "kv" && s.rows) {
    return `${h}<table class="kv"><tbody>${s.rows
      .map(([k, v]) => `<tr><th>${escapeHtml(k)}</th><td>${escapeHtml(v)}</td></tr>`)
      .join("")}</tbody></table>`;
  }
  if (s.kind === "table" && s.table) {
    const { columns, data } = s.table;
    return `${h}<table class="data"><thead><tr>${columns
      .map((c) => `<th>${escapeHtml(c)}</th>`)
      .join("")}</tr></thead><tbody>${data
      .map((row) => `<tr>${row.map((c) => `<td>${escapeHtml(c)}</td>`).join("")}</tr>`)
      .join("")}</tbody></table>`;
  }
  return h;
}

/** Open a branded printable HTML report and trigger the browser's PDF print dialog. */
export function exportToPDF(payload: ExportPayload) {
  const lang = payload.lang || "ar";
  const dir = lang === "en" ? "ltr" : "rtl";
  const html = `<!doctype html>
<html lang="${lang}" dir="${dir}">
<head>
<meta charset="utf-8"/>
<title>${escapeHtml(payload.title)} — ${BRAND}</title>
<style>
  @page { size: A4; margin: 18mm 14mm 22mm 14mm; }
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', Tahoma, Arial, sans-serif; color:#0f172a; margin:0; padding: 0 8px; line-height: 1.6; }
  header.brand { display:flex; align-items:center; gap:14px; padding: 10px 0 14px; border-bottom: 2px solid #1e40af; margin-bottom: 18px; }
  .brand-text { flex:1; }
  .brand-name { font-size: 22px; font-weight: 800; color:#0f2454; letter-spacing: .3px; }
  .brand-prev { font-size: 10px; font-weight: 600; color:#94a3b8; text-transform: uppercase; letter-spacing: 1.2px; margin-top: 2px; }
  .brand-sub { font-size: 11px; color:#64748b; margin-top: 2px; }
  .meta { font-size: 11px; color:#64748b; }
  h1 { font-size: 22px; margin: 6px 0 4px; color:#0f172a; }
  .subtitle { color:#475569; font-size: 13px; margin-bottom: 18px; }
  h2 { font-size: 15px; margin: 18px 0 8px; color:#4338ca; border-${dir === "rtl" ? "right" : "left"}: 4px solid #a855f7; padding-${dir === "rtl" ? "right" : "left"}: 8px; }
  p.prose { font-size: 12.5px; white-space: pre-wrap; }
  ul { padding-${dir === "rtl" ? "right" : "left"}: 18px; font-size: 12.5px; }
  li { margin: 3px 0; }
  table { width:100%; border-collapse: collapse; font-size: 12px; margin-top: 4px; }
  table.kv th { width: 30%; text-align:${dir === "rtl" ? "right" : "left"}; background:#f1f5f9; color:#334155; font-weight:600; padding:6px 8px; border:1px solid #e2e8f0; vertical-align: top; }
  table.kv td { padding:6px 8px; border:1px solid #e2e8f0; }
  table.data th { background:#4338ca; color:#fff; padding:6px 8px; border:1px solid #312e81; font-weight:600; text-align:${dir === "rtl" ? "right" : "left"}; }
  table.data td { padding:6px 8px; border:1px solid #e2e8f0; vertical-align: top; }
  table.data tr:nth-child(even) td { background:#f8fafc; }
  footer.disclaimer { margin-top: 28px; padding-top: 12px; border-top: 1px dashed #94a3b8; font-size: 10.5px; color:#475569; line-height: 1.5; }
  @media print { .noprint { display:none; } body { padding: 0; } }
  .noprint { position: fixed; top: 12px; ${dir === "rtl" ? "left" : "right"}: 12px; }
  .noprint button { background:#4338ca; color:#fff; border:0; padding:8px 14px; border-radius: 999px; font-size: 12px; cursor:pointer; box-shadow: 0 4px 12px rgba(67,56,202,.3); }
</style>
</head>
<body>
  <div class="noprint"><button onclick="window.print()">🖨️ ${dir === "rtl" ? "طباعة / حفظ PDF" : "Print / Save PDF"}</button></div>
  ${brandHeaderHtml(lang)}
  <h1>${escapeHtml(payload.title)}</h1>
  ${payload.subtitle ? `<div class="subtitle">${escapeHtml(payload.subtitle)}</div>` : ""}
  ${payload.sections.map(sectionHtml).join("")}
  <footer class="disclaimer">${escapeHtml(DISCLAIMER[lang])}</footer>
  <script>setTimeout(() => { try { window.focus(); window.print(); } catch(e){} }, 350);</script>
</body>
</html>`;

  const w = window.open("", "_blank", "noopener,noreferrer,width=900,height=1000");
  if (!w) {
    // Popup blocked — fallback: download html
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${payload.title}.html`;
    a.click();
    URL.revokeObjectURL(url);
    return;
  }
  w.document.open();
  w.document.write(html);
  w.document.close();
}

/** Build a branded multi-sheet Excel workbook and trigger download. */
export function exportToExcel(payload: ExportPayload) {
  const lang = payload.lang || "ar";
  const wb = XLSX.utils.book_new();

  const headerRows: any[][] = [
    [BRAND, "", "", ""],
    [PREVIOUS_BRAND, "", "", ""],
    [`${SITE} · ${ECOSYSTEM}`, "", "", ""],
    [`${UI[lang].generated}: ${new Date().toLocaleString()}`, "", "", ""],
    [payload.title, "", "", ""],
    payload.subtitle ? [payload.subtitle, "", "", ""] : ["", "", "", ""],
    [],
  ];

  // First sheet = summary with all KV/text/list, plus per-table sheets.
  const summary: any[][] = [...headerRows];

  payload.sections.forEach((s) => {
    summary.push([s.heading]);
    if (s.kind === "kv" && s.rows) {
      s.rows.forEach(([k, v]) => summary.push([k, v]));
    } else if (s.kind === "text" && s.text) {
      s.text.split("\n").forEach((line) => summary.push([line]));
    } else if (s.kind === "list" && s.list) {
      s.list.forEach((x) => summary.push(["•", x]));
    } else if (s.kind === "table" && s.table) {
      summary.push(s.table.columns);
      s.table.data.forEach((r) => summary.push(r));
    }
    summary.push([]);
  });

  summary.push([]);
  summary.push([DISCLAIMER[lang]]);

  const ws = XLSX.utils.aoa_to_sheet(summary);
  // Make first column wider for Arabic readability
  ws["!cols"] = [{ wch: 28 }, { wch: 60 }, { wch: 28 }, { wch: 28 }];
  XLSX.utils.book_append_sheet(wb, ws, "Report");

  // Add separate sheets per table section for richer data
  payload.sections.forEach((s, i) => {
    if (s.kind === "table" && s.table) {
      const sheetName = (s.heading || `Table ${i + 1}`).slice(0, 28).replace(/[\\/?*[\]:]/g, "_");
      const sws = XLSX.utils.aoa_to_sheet([s.table.columns, ...s.table.data]);
      sws["!cols"] = s.table.columns.map(() => ({ wch: 24 }));
      XLSX.utils.book_append_sheet(wb, sws, sheetName);
    }
  });

  const fileName = `${payload.title.replace(/[\\/?*[\]:]/g, "_")}-${new Date().toISOString().slice(0, 10)}.xlsx`;
  XLSX.writeFile(wb, fileName);
}

/** Build and download a CSV file. Flattens sections (kv/list/text/table) into rows. */
export function exportToCSV(payload: ExportPayload) {
  const lang = payload.lang || "ar";
  const lines: string[] = [];
  const esc = (v: any) => {
    const s = String(v ?? "");
    if (/[",\n;]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
    return s;
  };
  lines.push(esc(BRAND));
  lines.push(esc(payload.title));
  if (payload.subtitle) lines.push(esc(payload.subtitle));
  lines.push(esc(`${UI[lang].generated}: ${new Date().toLocaleString()}`));
  lines.push("");

  payload.sections.forEach((s) => {
    lines.push(esc(`# ${s.heading}`));
    if (s.kind === "kv" && s.rows) {
      lines.push(["key", "value"].map(esc).join(","));
      s.rows.forEach(([k, v]) => lines.push([esc(k), esc(v)].join(",")));
    } else if (s.kind === "text" && s.text) {
      s.text.split("\n").forEach((l) => lines.push(esc(l)));
    } else if (s.kind === "list" && s.list) {
      s.list.forEach((x) => lines.push(esc(x)));
    } else if (s.kind === "table" && s.table) {
      lines.push(s.table.columns.map(esc).join(","));
      s.table.data.forEach((r) => lines.push(r.map(esc).join(",")));
    }
    lines.push("");
  });
  lines.push(esc(DISCLAIMER[lang]));

  const csv = "\ufeff" + lines.join("\n"); // BOM for Excel UTF-8
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${payload.title.replace(/[\\/?*[\]:]/g, "_")}-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

/* ------------------------------------------------------------------ */
/* Part 18 — Export Center: JSON, Markdown, Word, PowerPoint.          */
/* Same ExportPayload shape as PDF/Excel/CSV — no parallel format.     */
/* ------------------------------------------------------------------ */

function download(content: BlobPart, mime: string, ext: string, title: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/[\\/?*[\]:]/g, "_")}-${new Date().toISOString().slice(0, 10)}.${ext}`;
  a.click();
  URL.revokeObjectURL(url);
}

/** Raw structured export — for pipelines and archiving. */
export function exportToJSON(payload: ExportPayload) {
  const lang = payload.lang || "ar";
  const body = JSON.stringify(
    { brand: BRAND, site: SITE, generated_at: new Date().toISOString(), language: lang, ...payload, disclaimer: DISCLAIMER[lang] },
    null, 2,
  );
  download(body, "application/json;charset=utf-8", "json", payload.title);
}

export function payloadToMarkdown(payload: ExportPayload): string {
  const lang = payload.lang || "ar";
  const out: string[] = [`# ${payload.title}`];
  if (payload.subtitle) out.push(`_${payload.subtitle}_`);
  out.push(`> ${BRAND} · ${SITE} — ${UI[lang].generated} ${new Date().toLocaleString()}`, "");
  for (const s of payload.sections) {
    out.push(`## ${s.heading}`);
    if (s.kind === "text" && s.text) out.push(s.text, "");
    else if (s.kind === "list" && s.list) out.push(...s.list.map((x) => `- ${x}`), "");
    else if (s.kind === "kv" && s.rows) {
      out.push("| | |", "|---|---|", ...s.rows.map(([k, v]) => `| ${k} | ${v} |`), "");
    } else if (s.kind === "table" && s.table) {
      out.push(
        `| ${s.table.columns.join(" | ")} |`,
        `| ${s.table.columns.map(() => "---").join(" | ")} |`,
        ...s.table.data.map((r) => `| ${r.join(" | ")} |`),
        "",
      );
    }
  }
  out.push("---", DISCLAIMER[lang]);
  return out.join("\n");
}

export function exportToMarkdown(payload: ExportPayload) {
  download(payloadToMarkdown(payload), "text/markdown;charset=utf-8", "md", payload.title);
}

/** Word-compatible HTML document (.doc) — opens natively in Word. */
export function exportToWord(payload: ExportPayload) {
  const lang = payload.lang || "ar";
  const dir = lang === "en" ? "ltr" : "rtl";
  const html = `<!doctype html><html lang="${lang}" dir="${dir}"><head><meta charset="utf-8"/>
<title>${escapeHtml(payload.title)}</title>
<style>body{font-family:Arial,sans-serif;direction:${dir}}h1{font-size:20pt}h2{font-size:14pt;margin-top:18pt}
table{border-collapse:collapse;width:100%}th,td{border:1px solid #999;padding:6px;font-size:10pt;text-align:${dir === "rtl" ? "right" : "left"}}
.small{color:#666;font-size:9pt}</style></head><body>
<h1>${escapeHtml(payload.title)}</h1>
${payload.subtitle ? `<p class="small">${escapeHtml(payload.subtitle)}</p>` : ""}
<p class="small">${BRAND} · ${SITE} — ${UI[lang].generated} ${escapeHtml(new Date().toLocaleString())}</p>
${payload.sections.map(sectionHtml).join("")}
<hr/><p class="small">${escapeHtml(DISCLAIMER[lang])}</p>
</body></html>`;
  download(html, "application/msword;charset=utf-8", "doc", payload.title);
}

/** Slide deck — one slide per section. Loaded lazily to keep the bundle light. */
export async function exportToPowerPoint(payload: ExportPayload) {
  const lang = payload.lang || "ar";
  const { default: PptxGenJS } = await import("pptxgenjs");
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_16x9";

  const cover = pptx.addSlide();
  cover.addText(payload.title, { x: 0.5, y: 2, w: 9, h: 1, fontSize: 30, bold: true, align: "center" });
  cover.addText(`${payload.subtitle || ""}\n${BRAND} · ${SITE}`, { x: 0.5, y: 3.1, w: 9, h: 1, fontSize: 14, align: "center", color: "666666" });

  for (const s of payload.sections) {
    const slide = pptx.addSlide();
    slide.addText(s.heading, { x: 0.4, y: 0.3, w: 9.2, h: 0.7, fontSize: 22, bold: true });
    if (s.kind === "table" && s.table) {
      slide.addTable(
        [s.table.columns.map((c) => ({ text: String(c), options: { bold: true } })), ...s.table.data.map((r) => r.map((c) => String(c)))] as any,
        { x: 0.4, y: 1.1, w: 9.2, fontSize: 10, border: { pt: 1, color: "CCCCCC" } },
      );
    } else {
      const body = s.kind === "kv" && s.rows ? s.rows.map(([k, v]) => `• ${k}: ${v}`).join("\n")
        : s.kind === "list" && s.list ? s.list.map((x) => `• ${x}`).join("\n")
        : s.text || "";
      slide.addText(body, { x: 0.4, y: 1.1, w: 9.2, h: 4, fontSize: 13, valign: "top" });
    }
  }

  const last = pptx.addSlide();
  last.addText(DISCLAIMER[lang], { x: 0.5, y: 2, w: 9, h: 2, fontSize: 10, color: "666666", align: "center" });

  await pptx.writeFile({ fileName: `${payload.title.replace(/[\\/?*[\]:]/g, "_")}-${new Date().toISOString().slice(0, 10)}.pptx` });
}
