/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PulseSourcesRouteImport } from './routes/pulse.sources'
import { Route as PulseCompareRouteImport } from './routes/pulse.compare'
import { Route as PulseAssistantRouteImport } from './routes/pulse.assistant'
import { Route as PulseGovRouteImport } from './routes/pulse.$gov'
import { Route as ApiWhatIfRouteImport } from './routes/api/what-if'
import { Route as ApiVisibilityRouteImport } from './routes/api/visibility'
import { Route as ApiSuggestRouteImport } from './routes/api/suggest'
import { Route as ApiSocialAnalysisRouteImport } from './routes/api/social-analysis'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiGeoStrategistRouteImport } from './routes/api/geo-strategist'
import { Route as ApiGeoRewriteRouteImport } from './routes/api/geo-rewrite'
import { Route as ApiFeasibilityRouteImport } from './routes/api/feasibility'
import { Route as ApiCompetitorMonitorRouteImport } from './routes/api/competitor-monitor'
import { Route as ApiCompareRouteImport } from './routes/api/compare'
import { Route as ApiCompanyEmailRouteImport } from './routes/api/company-email'
import { Route as ApiBrandBoostRouteImport } from './routes/api/brand-boost'
import { Route as ApiBrandAuthorityRouteImport } from './routes/api/brand-authority'
import { Route as ApiBizdevRouteImport } from './routes/api/bizdev'
import { Route as ApiAppliedRankingRouteImport } from './routes/api/applied-ranking'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as AdminPulseRouteImport } from './routes/admin_.pulse'
import { Route as ApiPublicHooksPulseCrawlRouteImport } from './routes/api/public/hooks/pulse-crawl'
import { Route as ApiPublicHooksAgentRunnerRouteImport } from './routes/api/public/hooks/agent-runner'
import { Route as ApiPublicBrandSlugRouteImport } from './routes/api/public/brand/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseSourcesRoute = PulseSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => PulseRoute,
} as any)
const PulseCompareRoute = PulseCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => PulseRoute,
} as any)
const PulseAssistantRoute = PulseAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PulseRoute,
} as any)
const PulseGovRoute = PulseGovRouteImport.update({
  id: '/$gov',
  path: '/$gov',
  getParentRoute: () => PulseRoute,
} as any)
const ApiWhatIfRoute = ApiWhatIfRouteImport.update({
  id: '/api/what-if',
  path: '/api/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisibilityRoute = ApiVisibilityRouteImport.update({
  id: '/api/visibility',
  path: '/api/visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestRoute = ApiSuggestRouteImport.update({
  id: '/api/suggest',
  path: '/api/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialAnalysisRoute = ApiSocialAnalysisRouteImport.update({
  id: '/api/social-analysis',
  path: '/api/social-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoStrategistRoute = ApiGeoStrategistRouteImport.update({
  id: '/api/geo-strategist',
  path: '/api/geo-strategist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoRewriteRoute = ApiGeoRewriteRouteImport.update({
  id: '/api/geo-rewrite',
  path: '/api/geo-rewrite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeasibilityRoute = ApiFeasibilityRouteImport.update({
  id: '/api/feasibility',
  path: '/api/feasibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorMonitorRoute = ApiCompetitorMonitorRouteImport.update({
  id: '/api/competitor-monitor',
  path: '/api/competitor-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompareRoute = ApiCompareRouteImport.update({
  id: '/api/compare',
  path: '/api/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanyEmailRoute = ApiCompanyEmailRouteImport.update({
  id: '/api/company-email',
  path: '/api/company-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandBoostRoute = ApiBrandBoostRouteImport.update({
  id: '/api/brand-boost',
  path: '/api/brand-boost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandAuthorityRoute = ApiBrandAuthorityRouteImport.update({
  id: '/api/brand-authority',
  path: '/api/brand-authority',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBizdevRoute = ApiBizdevRouteImport.update({
  id: '/api/bizdev',
  path: '/api/bizdev',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppliedRankingRoute = ApiAppliedRankingRouteImport.update({
  id: '/api/applied-ranking',
  path: '/api/applied-ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPulseRoute = AdminPulseRouteImport.update({
  id: '/admin_/pulse',
  path: '/admin/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPulseCrawlRoute =
  ApiPublicHooksPulseCrawlRouteImport.update({
    id: '/api/public/hooks/pulse-crawl',
    path: '/api/public/hooks/pulse-crawl',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentRunnerRoute =
  ApiPublicHooksAgentRunnerRouteImport.update({
    id: '/api/public/hooks/agent-runner',
    path: '/api/public/hooks/agent-runner',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBrandSlugRoute = ApiPublicBrandSlugRouteImport.update({
  id: '/api/public/brand/$slug',
  path: '/api/public/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/pulse': typeof PulseRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/pulse': typeof AdminPulseRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/applied-ranking': typeof ApiAppliedRankingRoute
  '/api/bizdev': typeof ApiBizdevRoute
  '/api/brand-authority': typeof ApiBrandAuthorityRoute
  '/api/brand-boost': typeof ApiBrandBoostRoute
  '/api/company-email': typeof ApiCompanyEmailRoute
  '/api/compare': typeof ApiCompareRoute
  '/api/competitor-monitor': typeof ApiCompetitorMonitorRoute
  '/api/feasibility': typeof ApiFeasibilityRoute
  '/api/geo-rewrite': typeof ApiGeoRewriteRoute
  '/api/geo-strategist': typeof ApiGeoStrategistRoute
  '/api/research': typeof ApiResearchRoute
  '/api/social-analysis': typeof ApiSocialAnalysisRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/visibility': typeof ApiVisibilityRoute
  '/api/what-if': typeof ApiWhatIfRoute
  '/pulse/$gov': typeof PulseGovRoute
  '/pulse/assistant': typeof PulseAssistantRoute
  '/pulse/compare': typeof PulseCompareRoute
  '/pulse/sources': typeof PulseSourcesRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/brand/$slug': typeof ApiPublicBrandSlugRoute
  '/api/public/hooks/agent-runner': typeof ApiPublicHooksAgentRunnerRoute
  '/api/public/hooks/pulse-crawl': typeof ApiPublicHooksPulseCrawlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/pulse': typeof PulseRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/pulse': typeof AdminPulseRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/applied-ranking': typeof ApiAppliedRankingRoute
  '/api/bizdev': typeof ApiBizdevRoute
  '/api/brand-authority': typeof ApiBrandAuthorityRoute
  '/api/brand-boost': typeof ApiBrandBoostRoute
  '/api/company-email': typeof ApiCompanyEmailRoute
  '/api/compare': typeof ApiCompareRoute
  '/api/competitor-monitor': typeof ApiCompetitorMonitorRoute
  '/api/feasibility': typeof ApiFeasibilityRoute
  '/api/geo-rewrite': typeof ApiGeoRewriteRoute
  '/api/geo-strategist': typeof ApiGeoStrategistRoute
  '/api/research': typeof ApiResearchRoute
  '/api/social-analysis': typeof ApiSocialAnalysisRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/visibility': typeof ApiVisibilityRoute
  '/api/what-if': typeof ApiWhatIfRoute
  '/pulse/$gov': typeof PulseGovRoute
  '/pulse/assistant': typeof PulseAssistantRoute
  '/pulse/compare': typeof PulseCompareRoute
  '/pulse/sources': typeof PulseSourcesRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/brand/$slug': typeof ApiPublicBrandSlugRoute
  '/api/public/hooks/agent-runner': typeof ApiPublicHooksAgentRunnerRoute
  '/api/public/hooks/pulse-crawl': typeof ApiPublicHooksPulseCrawlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/guide': typeof GuideRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/pulse': typeof PulseRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin_/pulse': typeof AdminPulseRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/applied-ranking': typeof ApiAppliedRankingRoute
  '/api/bizdev': typeof ApiBizdevRoute
  '/api/brand-authority': typeof ApiBrandAuthorityRoute
  '/api/brand-boost': typeof ApiBrandBoostRoute
  '/api/company-email': typeof ApiCompanyEmailRoute
  '/api/compare': typeof ApiCompareRoute
  '/api/competitor-monitor': typeof ApiCompetitorMonitorRoute
  '/api/feasibility': typeof ApiFeasibilityRoute
  '/api/geo-rewrite': typeof ApiGeoRewriteRoute
  '/api/geo-strategist': typeof ApiGeoStrategistRoute
  '/api/research': typeof ApiResearchRoute
  '/api/social-analysis': typeof ApiSocialAnalysisRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/visibility': typeof ApiVisibilityRoute
  '/api/what-if': typeof ApiWhatIfRoute
  '/pulse/$gov': typeof PulseGovRoute
  '/pulse/assistant': typeof PulseAssistantRoute
  '/pulse/compare': typeof PulseCompareRoute
  '/pulse/sources': typeof PulseSourcesRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/brand/$slug': typeof ApiPublicBrandSlugRoute
  '/api/public/hooks/agent-runner': typeof ApiPublicHooksAgentRunnerRoute
  '/api/public/hooks/pulse-crawl': typeof ApiPublicHooksPulseCrawlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/guide'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/pulse'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/pulse'
    | '/api/analyze'
    | '/api/applied-ranking'
    | '/api/bizdev'
    | '/api/brand-authority'
    | '/api/brand-boost'
    | '/api/company-email'
    | '/api/compare'
    | '/api/competitor-monitor'
    | '/api/feasibility'
    | '/api/geo-rewrite'
    | '/api/geo-strategist'
    | '/api/research'
    | '/api/social-analysis'
    | '/api/suggest'
    | '/api/visibility'
    | '/api/what-if'
    | '/pulse/$gov'
    | '/pulse/assistant'
    | '/pulse/compare'
    | '/pulse/sources'
    | '/u/$username'
    | '/api/public/brand/$slug'
    | '/api/public/hooks/agent-runner'
    | '/api/public/hooks/pulse-crawl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/guide'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/pulse'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/pulse'
    | '/api/analyze'
    | '/api/applied-ranking'
    | '/api/bizdev'
    | '/api/brand-authority'
    | '/api/brand-boost'
    | '/api/company-email'
    | '/api/compare'
    | '/api/competitor-monitor'
    | '/api/feasibility'
    | '/api/geo-rewrite'
    | '/api/geo-strategist'
    | '/api/research'
    | '/api/social-analysis'
    | '/api/suggest'
    | '/api/visibility'
    | '/api/what-if'
    | '/pulse/$gov'
    | '/pulse/assistant'
    | '/pulse/compare'
    | '/pulse/sources'
    | '/u/$username'
    | '/api/public/brand/$slug'
    | '/api/public/hooks/agent-runner'
    | '/api/public/hooks/pulse-crawl'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/guide'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/pulse'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin_/pulse'
    | '/api/analyze'
    | '/api/applied-ranking'
    | '/api/bizdev'
    | '/api/brand-authority'
    | '/api/brand-boost'
    | '/api/company-email'
    | '/api/compare'
    | '/api/competitor-monitor'
    | '/api/feasibility'
    | '/api/geo-rewrite'
    | '/api/geo-strategist'
    | '/api/research'
    | '/api/social-analysis'
    | '/api/suggest'
    | '/api/visibility'
    | '/api/what-if'
    | '/pulse/$gov'
    | '/pulse/assistant'
    | '/pulse/compare'
    | '/pulse/sources'
    | '/u/$username'
    | '/api/public/brand/$slug'
    | '/api/public/hooks/agent-runner'
    | '/api/public/hooks/pulse-crawl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  GuideRoute: typeof GuideRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PulseRoute: typeof PulseRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminPulseRoute: typeof AdminPulseRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiAppliedRankingRoute: typeof ApiAppliedRankingRoute
  ApiBizdevRoute: typeof ApiBizdevRoute
  ApiBrandAuthorityRoute: typeof ApiBrandAuthorityRoute
  ApiBrandBoostRoute: typeof ApiBrandBoostRoute
  ApiCompanyEmailRoute: typeof ApiCompanyEmailRoute
  ApiCompareRoute: typeof ApiCompareRoute
  ApiCompetitorMonitorRoute: typeof ApiCompetitorMonitorRoute
  ApiFeasibilityRoute: typeof ApiFeasibilityRoute
  ApiGeoRewriteRoute: typeof ApiGeoRewriteRoute
  ApiGeoStrategistRoute: typeof ApiGeoStrategistRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ApiSocialAnalysisRoute: typeof ApiSocialAnalysisRoute
  ApiSuggestRoute: typeof ApiSuggestRoute
  ApiVisibilityRoute: typeof ApiVisibilityRoute
  ApiWhatIfRoute: typeof ApiWhatIfRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicBrandSlugRoute: typeof ApiPublicBrandSlugRoute
  ApiPublicHooksAgentRunnerRoute: typeof ApiPublicHooksAgentRunnerRoute
  ApiPublicHooksPulseCrawlRoute: typeof ApiPublicHooksPulseCrawlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse/sources': {
      id: '/pulse/sources'
      path: '/sources'
      fullPath: '/pulse/sources'
      preLoaderRoute: typeof PulseSourcesRouteImport
      parentRoute: typeof PulseRoute
    }
    '/pulse/compare': {
      id: '/pulse/compare'
      path: '/compare'
      fullPath: '/pulse/compare'
      preLoaderRoute: typeof PulseCompareRouteImport
      parentRoute: typeof PulseRoute
    }
    '/pulse/assistant': {
      id: '/pulse/assistant'
      path: '/assistant'
      fullPath: '/pulse/assistant'
      preLoaderRoute: typeof PulseAssistantRouteImport
      parentRoute: typeof PulseRoute
    }
    '/pulse/$gov': {
      id: '/pulse/$gov'
      path: '/$gov'
      fullPath: '/pulse/$gov'
      preLoaderRoute: typeof PulseGovRouteImport
      parentRoute: typeof PulseRoute
    }
    '/api/what-if': {
      id: '/api/what-if'
      path: '/api/what-if'
      fullPath: '/api/what-if'
      preLoaderRoute: typeof ApiWhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visibility': {
      id: '/api/visibility'
      path: '/api/visibility'
      fullPath: '/api/visibility'
      preLoaderRoute: typeof ApiVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest': {
      id: '/api/suggest'
      path: '/api/suggest'
      fullPath: '/api/suggest'
      preLoaderRoute: typeof ApiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social-analysis': {
      id: '/api/social-analysis'
      path: '/api/social-analysis'
      fullPath: '/api/social-analysis'
      preLoaderRoute: typeof ApiSocialAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo-strategist': {
      id: '/api/geo-strategist'
      path: '/api/geo-strategist'
      fullPath: '/api/geo-strategist'
      preLoaderRoute: typeof ApiGeoStrategistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo-rewrite': {
      id: '/api/geo-rewrite'
      path: '/api/geo-rewrite'
      fullPath: '/api/geo-rewrite'
      preLoaderRoute: typeof ApiGeoRewriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feasibility': {
      id: '/api/feasibility'
      path: '/api/feasibility'
      fullPath: '/api/feasibility'
      preLoaderRoute: typeof ApiFeasibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitor-monitor': {
      id: '/api/competitor-monitor'
      path: '/api/competitor-monitor'
      fullPath: '/api/competitor-monitor'
      preLoaderRoute: typeof ApiCompetitorMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compare': {
      id: '/api/compare'
      path: '/api/compare'
      fullPath: '/api/compare'
      preLoaderRoute: typeof ApiCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/company-email': {
      id: '/api/company-email'
      path: '/api/company-email'
      fullPath: '/api/company-email'
      preLoaderRoute: typeof ApiCompanyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-boost': {
      id: '/api/brand-boost'
      path: '/api/brand-boost'
      fullPath: '/api/brand-boost'
      preLoaderRoute: typeof ApiBrandBoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-authority': {
      id: '/api/brand-authority'
      path: '/api/brand-authority'
      fullPath: '/api/brand-authority'
      preLoaderRoute: typeof ApiBrandAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bizdev': {
      id: '/api/bizdev'
      path: '/api/bizdev'
      fullPath: '/api/bizdev'
      preLoaderRoute: typeof ApiBizdevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applied-ranking': {
      id: '/api/applied-ranking'
      path: '/api/applied-ranking'
      fullPath: '/api/applied-ranking'
      preLoaderRoute: typeof ApiAppliedRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/pulse': {
      id: '/admin_/pulse'
      path: '/admin/pulse'
      fullPath: '/admin/pulse'
      preLoaderRoute: typeof AdminPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pulse-crawl': {
      id: '/api/public/hooks/pulse-crawl'
      path: '/api/public/hooks/pulse-crawl'
      fullPath: '/api/public/hooks/pulse-crawl'
      preLoaderRoute: typeof ApiPublicHooksPulseCrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agent-runner': {
      id: '/api/public/hooks/agent-runner'
      path: '/api/public/hooks/agent-runner'
      fullPath: '/api/public/hooks/agent-runner'
      preLoaderRoute: typeof ApiPublicHooksAgentRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brand/$slug': {
      id: '/api/public/brand/$slug'
      path: '/api/public/brand/$slug'
      fullPath: '/api/public/brand/$slug'
      preLoaderRoute: typeof ApiPublicBrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PulseRouteChildren {
  PulseGovRoute: typeof PulseGovRoute
  PulseAssistantRoute: typeof PulseAssistantRoute
  PulseCompareRoute: typeof PulseCompareRoute
  PulseSourcesRoute: typeof PulseSourcesRoute
}

const PulseRouteChildren: PulseRouteChildren = {
  PulseGovRoute: PulseGovRoute,
  PulseAssistantRoute: PulseAssistantRoute,
  PulseCompareRoute: PulseCompareRoute,
  PulseSourcesRoute: PulseSourcesRoute,
}

const PulseRouteWithChildren = PulseRoute._addFileChildren(PulseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  GuideRoute: GuideRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PulseRoute: PulseRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminPulseRoute: AdminPulseRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiAppliedRankingRoute: ApiAppliedRankingRoute,
  ApiBizdevRoute: ApiBizdevRoute,
  ApiBrandAuthorityRoute: ApiBrandAuthorityRoute,
  ApiBrandBoostRoute: ApiBrandBoostRoute,
  ApiCompanyEmailRoute: ApiCompanyEmailRoute,
  ApiCompareRoute: ApiCompareRoute,
  ApiCompetitorMonitorRoute: ApiCompetitorMonitorRoute,
  ApiFeasibilityRoute: ApiFeasibilityRoute,
  ApiGeoRewriteRoute: ApiGeoRewriteRoute,
  ApiGeoStrategistRoute: ApiGeoStrategistRoute,
  ApiResearchRoute: ApiResearchRoute,
  ApiSocialAnalysisRoute: ApiSocialAnalysisRoute,
  ApiSuggestRoute: ApiSuggestRoute,
  ApiVisibilityRoute: ApiVisibilityRoute,
  ApiWhatIfRoute: ApiWhatIfRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicBrandSlugRoute: ApiPublicBrandSlugRoute,
  ApiPublicHooksAgentRunnerRoute: ApiPublicHooksAgentRunnerRoute,
  ApiPublicHooksPulseCrawlRoute: ApiPublicHooksPulseCrawlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
